### ISSUE TITLE
Big hairy exception backtrace with rouge 2.0

### ISSUE THREAD

**Issue by syskill** [r7kamura/plz#6]
```
syskill@blackkingbar:my_api_client(master)$ bundle exec plz list widget
/home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/rouge-2.0.7/lib/rouge/formatters/terminal256.rb:161:in `get_style': undefined method `get_own_style' for {:theme=>"github"}:Hash (NoMethodError)
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/rouge-2.0.7/lib/rouge/formatters/terminal256.rb:155:in `escape_sequence'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/rouge-2.0.7/lib/rouge/formatters/terminal256.rb:18:in `block in stream'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/rouge-2.0.7/lib/rouge/lexer.rb:315:in `block in lex'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/rouge-2.0.7/lib/rouge/regex_lexer.rb:126:in `block in rule'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/rouge-2.0.7/lib/rouge/regex_lexer.rb:305:in `instance_exec'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/rouge-2.0.7/lib/rouge/regex_lexer.rb:305:in `block in step'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/rouge-2.0.7/lib/rouge/regex_lexer.rb:287:in `each'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/rouge-2.0.7/lib/rouge/regex_lexer.rb:287:in `step'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/rouge-2.0.7/lib/rouge/regex_lexer.rb:290:in `block in step'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/rouge-2.0.7/lib/rouge/regex_lexer.rb:287:in `each'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/rouge-2.0.7/lib/rouge/regex_lexer.rb:287:in `step'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/rouge-2.0.7/lib/rouge/regex_lexer.rb:268:in `stream_tokens'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/rouge-2.0.7/lib/rouge/lexer.rb:307:in `lex'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/rouge-2.0.7/lib/rouge/formatters/terminal256.rb:17:in `each'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/rouge-2.0.7/lib/rouge/formatters/terminal256.rb:17:in `stream'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/rouge-2.0.7/lib/rouge/formatter.rb:37:in `format'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/rouge-2.0.7/lib/rouge/formatter.rb:25:in `format'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/plz-0.1.5/lib/plz/response_renderer.rb:74:in `body'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/plz-0.1.5/lib/plz/response_renderer.rb:29:in `call'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/plz-0.1.5/lib/plz/response_renderer.rb:5:in `call'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/plz-0.1.5/lib/plz/commands/request.rb:22:in `call'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/gems/plz-0.1.5/bin/plz:6:in `<top (required)>'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/bin/plz:23:in `load'
	from /home/syskill/src/my_api_client/vendor/bundle/ruby/2.3.0/bin/plz:23:in `<main>'
```

Works fine when I downgrade to rouge 1.11.1, or when I add `--no-color` to the command line.

**Comment by r7kamura** [comment]
Thanks for your reporting! I'll fix the version of rouge gem with `< 2.0.0` for now.
